emm_user:
    resource: "@EMMUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
emm_user_index:
    path:       /user/index
    defaults: { _controller: EMMUserBundle:User:renderindex }

emm_user_index_data:
    path:       /user/indexData
    defaults: { _controller: EMMUserBundle:User:index }
    condition:  "request.isXmlHttpRequest()"

emm_user_add:
    path:     /user/add
    defaults: { _controller: EMMUserBundle:User:add }
    
emm_user_create:
    path:     /user/create
    defaults: { _controller: EMMUserBundle:User:create }
    methods: POST

emm_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: EMMUserBundle:User:edit }

emm_user_update:
    path:     /user/update/{id}
    defaults: { _controller: EMMUserBundle:User:update }
    methods: [POST, PUT]

emm_user_redirect_edit:
    path: /user/update/{id}
    defaults:
        _controller: EMMUserBundle:User:edit
        path: /user/edit/{id}

emm_user_view:
    path:     /user/view/{id}
    defaults: { _controller: EMMUserBundle:User:view }

emm_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: EMMUserBundle:User:delete }
    methods: [GET, POST, DELETE]
    
emm_user_redirect_add:
    path: /user/create
    defaults:
        _controller: EMMUserBundle:User:add
        path: /user/add
        permanent: true
